"""
Champion data utility for team composition analysis.
Contains information about champion roles and damage types.
"""

# Champion roles mapping
# Roles: Tank, Fighter, Assassin, Mage, Marksman, Support
CHAMPION_ROLES = {
    # Tanks
    "Alistar": "Tank",
    "Amumu": "Tank",
    "Braum": "Tank",
    "Cho'Gath": "Tank",
    "Dr. Mundo": "Tank",
    "Galio": "Tank",
    "Leona": "Tank",
    "Malphite": "Tank",
    "Maokai": "Tank",
    "Nautilus": "Tank",
    "Nunu & Willump": "Tank",
    "Ornn": "Tank",
    "Poppy": "Tank",
    "Rammus": "Tank",
    "Sejuani": "Tank",
    "Shen": "Tank",
    "Sion": "Tank",
    "Tahm Kench": "Tank",
    "Zac": "Tank",
    
    # Fighters
    "Aatrox": "Fighter",
    "Camille": "Fighter",
    "Darius": "Fighter",
    "Fiora": "Fighter",
    "Gangplank": "Fighter",
    "Garen": "Fighter",
    "Gnar": "Fighter",
    "Hecarim": "Fighter",
    "Illaoi": "Fighter",
    "Irelia": "Fighter",
    "Jax": "Fighter",
    "Jayce": "Fighter",
    "Kayle": "Fighter",
    "Kled": "Fighter",
    "Lee Sin": "Fighter",
    "Mordekaiser": "Fighter",
    "Nasus": "Fighter",
    "Olaf": "Fighter",
    "Pantheon": "Fighter",
    "Renekton": "Fighter",
    "Rengar": "Fighter",
    "Riven": "Fighter",
    "Rumble": "Fighter",
    "Sett": "Fighter",
    "Shyvana": "Fighter",
    "Singed": "Fighter",
    "Trundle": "Fighter",
    "Tryndamere": "Fighter",
    "Udyr": "Fighter",
    "Urgot": "Fighter",
    "Vi": "Fighter",
    "Volibear": "Fighter",
    "Warwick": "Fighter",
    "Wukong": "Fighter",
    "Xin Zhao": "Fighter",
    "Yorick": "Fighter",
    
    # Assassins
    "Akali": "Assassin",
    "Diana": "Assassin",
    "Ekko": "Assassin",
    "Evelynn": "Assassin",
    "Fizz": "Assassin",
    "Kassadin": "Assassin",
    "Katarina": "Assassin",
    "Kha'Zix": "Assassin",
    "LeBlanc": "Assassin",
    "Nocturne": "Assassin",
    "Pyke": "Assassin",
    "Qiyana": "Assassin",
    "Shaco": "Assassin",
    "Talon": "Assassin",
    "Zed": "Assassin",
    
    # Mages
    "Ahri": "Mage",
    "Anivia": "Mage",
    "Annie": "Mage",
    "Aurelion Sol": "Mage",
    "Azir": "Mage",
    "Brand": "Mage",
    "Cassiopeia": "Mage",
    "Fiddlesticks": "Mage",
    "Gragas": "Mage",
    "Heimerdinger": "Mage",
    "Karma": "Mage",
    "Karthus": "Mage",
    "Kennen": "Mage",
    "Lissandra": "Mage",
    "Lux": "Mage",
    "Malzahar": "Mage",
    "Morgana": "Mage",
    "Neeko": "Mage",
    "Orianna": "Mage",
    "Ryze": "Mage",
    "Swain": "Mage",
    "Sylas": "Mage",
    "Syndra": "Mage",
    "Taliyah": "Mage",
    "Twisted Fate": "Mage",
    "Veigar": "Mage",
    "Vel'Koz": "Mage",
    "Viktor": "Mage",
    "Vladimir": "Mage",
    "Xerath": "Mage",
    "Ziggs": "Mage",
    "Zilean": "Mage",
    "Zoe": "Mage",
    "Zyra": "Mage",
    
    # Marksmen
    "Aphelios": "Marksman",
    "Ashe": "Marksman",
    "Caitlyn": "Marksman",
    "Corki": "Marksman",
    "Draven": "Marksman",
    "Ezreal": "Marksman",
    "Graves": "Marksman",
    "Jhin": "Marksman",
    "Jinx": "Marksman",
    "Kai'Sa": "Marksman",
    "Kalista": "Marksman",
    "Kindred": "Marksman",
    "Kog'Maw": "Marksman",
    "Lucian": "Marksman",
    "Miss Fortune": "Marksman",
    "Quinn": "Marksman",
    "Samira": "Marksman",
    "Senna": "Marksman",
    "Sivir": "Marksman",
    "Teemo": "Marksman",
    "Tristana": "Marksman",
    "Twitch": "Marksman",
    "Varus": "Marksman",
    "Vayne": "Marksman",
    "Xayah": "Marksman",
    
    # Supports
    "Bard": "Support",
    "Blitzcrank": "Support",
    "Ivern": "Support",
    "Janna": "Support",
    "Lulu": "Support",
    "Nami": "Support",
    "Rakan": "Support",
    "Seraphine": "Support",
    "Sona": "Support",
    "Soraka": "Support",
    "Taric": "Support",
    "Thresh": "Support",
    "Yuumi": "Support",
}

# Champion damage types mapping
# AP: Ability Power (magic damage)
# AD: Attack Damage (physical damage)
CHAMPION_DAMAGE_TYPES = {
    # AP Champions
    "Ahri": "AP",
    "Amumu": "AP",
    "Anivia": "AP",
    "Annie": "AP",
    "Aurelion Sol": "AP",
    "Azir": "AP",
    "Bard": "AP",
    "Brand": "AP",
    "Cassiopeia": "AP",
    "Cho'Gath": "AP",
    "Diana": "AP",
    "Ekko": "AP",
    "Elise": "AP",
    "Evelynn": "AP",
    "Fiddlesticks": "AP",
    "Fizz": "AP",
    "Galio": "AP",
    "Gragas": "AP",
    "Heimerdinger": "AP",
    "Ivern": "AP",
    "Janna": "AP",
    "Karma": "AP",
    "Karthus": "AP",
    "Kassadin": "AP",
    "Katarina": "AP",
    "Kennen": "AP",
    "Kog'Maw": "AP",
    "LeBlanc": "AP",
    "Lissandra": "AP",
    "Lulu": "AP",
    "Lux": "AP",
    "Malphite": "AP",
    "Malzahar": "AP",
    "Maokai": "AP",
    "Mordekaiser": "AP",
    "Morgana": "AP",
    "Nami": "AP",
    "Neeko": "AP",
    "Nidalee": "AP",
    "Orianna": "AP",
    "Rumble": "AP",
    "Ryze": "AP",
    "Seraphine": "AP",
    "Shyvana": "AP",
    "Singed": "AP",
    "Sona": "AP",
    "Soraka": "AP",
    "Swain": "AP",
    "Sylas": "AP",
    "Syndra": "AP",
    "Taliyah": "AP",
    "Teemo": "AP",
    "Twisted Fate": "AP",
    "Veigar": "AP",
    "Vel'Koz": "AP",
    "Viktor": "AP",
    "Vladimir": "AP",
    "Xerath": "AP",
    "Yuumi": "AP",
    "Ziggs": "AP",
    "Zilean": "AP",
    "Zoe": "AP",
    "Zyra": "AP",
    
    # AD Champions
    "Aatrox": "AD",
    "Aphelios": "AD",
    "Ashe": "AD",
    "Caitlyn": "AD",
    "Camille": "AD",
    "Corki": "AD",
    "Darius": "AD",
    "Draven": "AD",
    "Dr. Mundo": "AD",
    "Ezreal": "AD",
    "Fiora": "AD",
    "Gangplank": "AD",
    "Garen": "AD",
    "Gnar": "AD",
    "Graves": "AD",
    "Hecarim": "AD",
    "Illaoi": "AD",
    "Irelia": "AD",
    "Jax": "AD",
    "Jayce": "AD",
    "Jhin": "AD",
    "Jinx": "AD",
    "Kai'Sa": "AD",
    "Kalista": "AD",
    "Kha'Zix": "AD",
    "Kindred": "AD",
    "Kled": "AD",
    "Lee Sin": "AD",
    "Lucian": "AD",
    "Master Yi": "AD",
    "Miss Fortune": "AD",
    "Nasus": "AD",
    "Nautilus": "AD",
    "Nocturne": "AD",
    "Olaf": "AD",
    "Pantheon": "AD",
    "Pyke": "AD",
    "Qiyana": "AD",
    "Quinn": "AD",
    "Rakan": "AD",
    "Rammus": "AD",
    "Renekton": "AD",
    "Rengar": "AD",
    "Riven": "AD",
    "Samira": "AD",
    "Sejuani": "AD",
    "Senna": "AD",
    "Sett": "AD",
    "Shaco": "AD",
    "Shen": "AD",
    "Sion": "AD",
    "Sivir": "AD",
    "Talon": "AD",
    "Taric": "AD",
    "Thresh": "AD",
    "Tristana": "AD",
    "Trundle": "AD",
    "Tryndamere": "AD",
    "Twitch": "AD",
    "Udyr": "AD",
    "Urgot": "AD",
    "Varus": "AD",
    "Vayne": "AD",
    "Vi": "AD",
    "Volibear": "AD",
    "Warwick": "AD",
    "Wukong": "AD",
    "Xayah": "AD",
    "Xin Zhao": "AD",
    "Yasuo": "AD",
    "Yone": "AD",
    "Yorick": "AD",
    "Zac": "AD",
    "Zed": "AD",
}

# Team synergies based on champion combinations
TEAM_SYNERGIES = {
    "Engage Combo": [
        {"Malphite", "Orianna"},
        {"Amumu", "Miss Fortune"},
        {"Leona", "Yasuo"},
        {"Galio", "Camille"},
    ],
    "Poke Composition": [
        {"Jayce", "Ziggs", "Xerath"},
        {"Ezreal", "Lux", "Vel'Koz"},
        {"Varus", "Zoe", "Nidalee"},
    ],
    "Protect the Carry": [
        {"Lulu", "Kog'Maw"},
        {"Lulu", "Jinx"},
        {"Janna", "Vayne"},
        {"Taric", "Master Yi"},
    ],
    "Wombo Combo": [
        {"Malphite", "Yasuo", "Orianna"},
        {"Amumu", "Miss Fortune", "Galio"},
        {"Sona", "Seraphine", "Miss Fortune"},
    ],
}

def get_champion_role(champion_name):
    """Get the role of a champion by name."""
    return CHAMPION_ROLES.get(champion_name, "Unknown")

def get_champion_damage_type(champion_name):
    """Get the damage type of a champion by name."""
    return CHAMPION_DAMAGE_TYPES.get(champion_name, "Unknown")

def get_team_synergies(champion_names):
    """
    Identify team synergies based on champion combinations.
    
    Args:
        champion_names: List of champion names in the team
    
    Returns:
        List of synergy names that apply to this team
    """
    champion_set = set(champion_names)
    synergies = []
    
    for synergy_name, synergy_combos in TEAM_SYNERGIES.items():
        for combo in synergy_combos:
            if combo.issubset(champion_set):
                synergies.append(synergy_name)
                break
    
    return synergies