# Generated by Django 4.2.15 on 2024-08-13 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champion_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('game_start', models.DateTimeField()),
                ('game_duration', models.IntegerField()),
                ('game_mode', models.CharField(max_length=50)),
                ('game_version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileIcon',
            fields=[
                ('profile_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('puuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=50)),
                ('tag_line', models.CharField(max_length=10)),
                ('summoner_level', models.IntegerField()),
                ('profile_icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='match_history.profileicon')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='match_history.champion')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='match_history.match')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='match_history.summoner')),
            ],
        ),
    ]
