# Generated by Django 4.2.15 on 2024-08-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champion_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileIcon',
            fields=[
                ('profile_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('puid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('summoner_id', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('gameName', models.CharField(max_length=50)),
                ('tagLine', models.CharField(max_length=10)),
                ('summoner_level', models.IntegerField()),
                ('profile_icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='match_history.profileicon')),
            ],
        ),
    ]
