# Generated by Django 4.2.15 on 2024-08-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='id',
        ),
        migrations.AlterField(
            model_name='champion',
            name='champion_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
