# Generated by Django 4.2.15 on 2024-08-13 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='game_creation',
            new_name='game_start',
        ),
    ]
