# Generated by Django 4.2.15 on 2024-08-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0002_remove_champion_id_alter_champion_champion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='champion_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
