# Generated by Django 4.2.15 on 2024-08-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0003_alter_champion_champion_id_alter_champion_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
    ]
